### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by Anzo52** [Anzo52/miniartmaker#2]
Need to test

**Comment by Anzo52** [comment]
Testing produced following error:
`Traceback (most recent call last):
  File "pixelartmaker.py", line 79, in <module>
    main(args.size, args.crypto_creeps, args.image_size)
  File "pixelartmaker.py", line 64, in main
    make_crypto_creep(border, draw, size)
  File "pixelartmaker.py", line 35, in make_crypto_creep
    rando_col = [rando_col(), rando_col(), rando_col(), (0,0,0), (0,0,0), (0,0,0)]  # list of colors
UnboundLocalError: local variable 'rando_col' referenced before assignment`

**Comment by Anzo52** [comment]
Fixed above error by changing "rando_col" to "rando_col_gen" on line 25
