### ISSUE TITLE
pop from empty list 

### ISSUE THREAD

**Issue by Anzo52** [Anzo52/miniartmaker#4]
Traceback (most recent call last):
  File "pixelartmaker.py", line 78, in <module>
    main(args.size, args.crypto_creeps, args.image_size)
  File "pixelartmaker.py", line 63, in main
    make_crypto_creep(border, draw, size)
  File "pixelartmaker.py", line 44, in make_crypto_creep
    make_square((top_left_x, top_left_y, bottom_right_x, bottom_right_y), draw, rando_col[element], i, size)
  File "pixelartmaker.py", line 24, in make_square
    draw.rectangle(border, symbol_list.pop())
IndexError: pop from empty list

**Comment by Anzo52** [comment]
fixed
